# Generated by Django 3.2 on 2021-09-06 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0006_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(choices=[('Cutlery', 'Cutlery'), ('Equipment', 'Equipment'), ('Essentials', 'Essentials')], max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category'),
        ),
    ]
