# Generated by Django 3.2 on 2021-09-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0009_alter_stock_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories'},
        ),
    ]
